// data
exports.data = [
  {
    grade: 0,
    time: '202102',
    name: '形势与政策',
    type: '公共必修',
    credit: '2',
    score: '82.25',
  },
  {
    grade: 0,
    time: '202102',
    name: '形势与政策（八）',
    type: '公共必修',
    credit: '0',
    score: '85',
  },
  {
    grade: 0,
    time: '202102',
    name: '毕业设计（卓越）',
    type: '毕业设计',
    credit: '10',
    score: 80,
  },
  {
    grade: 0,
    time: '202102',
    name: '毕业实习（卓越）',
    type: '毕业实习',
    credit: '2',
    score: 90,
  },
  {
    grade: 0,
    time: '202101',
    name: '形势与政策（七）',
    type: '公共必修',
    credit: '0',
    score: '79',
  },
  {
    grade: 0,
    time: '202101',
    name: '智能创新设计与创业实践',
    type: '创新创业与素质拓展',
    credit: '2',
    score: 60,
  },
  {
    grade: 0,
    time: '202101',
    name: '电气工程实践A',
    type: '实践环节',
    credit: '2',
    score: '68',
  },
  {
    grade: 0,
    time: '202101',
    name: '企业实践',
    type: '实践环节',
    credit: '7',
    score: 70,
  },
  {
    grade: 0,
    time: '202002',
    name: '大学生就业与创业指导',
    type: '公共必修',
    credit: '0.5',
    score: '86',
  },
  {
    grade: 0,
    time: '202002',
    name: '形势与政策（六）',
    type: '公共必修',
    credit: '0',
    score: '80',
  },
  {
    grade: 0,
    time: '202002',
    name: '编译原理',
    type: '学科必修',
    credit: '2.5',
    score: '73',
  },
  {
    grade: 0,
    time: '202002',
    name: '计算方法',
    type: '学科必修',
    credit: '2',
    score: '70',
  },
  {
    grade: 0,
    time: '202002',
    name: '计算机系统结构',
    type: '学科必修',
    credit: '2.5',
    score: '76',
  },
  {
    grade: 0,
    time: '202002',
    name: '高级人工智能',
    type: '专业方向（限选）1',
    credit: '2',
    score: '70',
  },
  {
    grade: 0,
    time: '202002',
    name: '计算机动画与游戏设计基础',
    type: '专业方向（限选）1',
    credit: '2',
    score: '71',
  },
  {
    grade: 0,
    time: '202002',
    name: '企业专家系列讲座',
    type: '专业方向（限选）1',
    credit: '1',
    score: 80,
  },
  {
    grade: 0,
    time: '202002',
    name: '数据挖掘技术',
    type: '专业方向（限选）1',
    credit: '2',
    score: '76',
  },
  {
    grade: 0,
    time: '202002',
    name: '单片机原理及应用',
    type: '专业选修',
    credit: '3',
    score: '60',
  },
  {
    grade: 0,
    time: '202002',
    name: '编译系统设计实践',
    type: '实践环节',
    credit: '1',
    score: '80',
  },
  {
    grade: 0,
    time: '202001',
    name: '大学应用写作',
    type: '公共必修',
    credit: '1',
    score: '80',
  },
  {
    grade: 0,
    time: '202001',
    name: '形势与政策（五）',
    type: '公共必修',
    credit: '0',
    score: '80',
  },
  {
    grade: 0,
    time: '202001',
    name: '计算机操作系统',
    type: '学科必修',
    credit: '3.5',
    score: '74',
  },
  {
    grade: 0,
    time: '202001',
    name: '人工智能',
    type: '学科必修',
    credit: '2',
    score: '74',
  },
  {
    grade: 0,
    time: '202001',
    name: '软件工程A',
    type: '学科必修',
    credit: '2.5',
    score: '79',
  },
  {
    grade: 0,
    time: '202001',
    name: '数据库系统原理',
    type: '学科必修',
    credit: '3.5',
    score: '51',
  },
  {
    grade: 0,
    time: '202001',
    name: '数据库系统原理',
    type: '学科必修',
    credit: '3.5',
    score: '70',
  },
  {
    grade: 0,
    time: '202001',
    name: '计算机图形学',
    type: '专业方向（限选）1',
    credit: '2',
    score: '61',
  },
  {
    grade: 0,
    time: '202001',
    name: '网络程序设计',
    type: '专业方向（限选）3',
    credit: '2',
    score: '82',
  },
  {
    grade: 0,
    time: '202001',
    name: '面向对象分析与设计',
    type: '专业方向（限选）4',
    credit: '2',
    score: '69',
  },
  {
    grade: 0,
    time: '202001',
    name: '摄影基础',
    type: '文学与艺术类',
    credit: '1.5',
    score: 80,
  },
  {
    grade: 0,
    time: '202001',
    name: '超星尔雅：创新中国',
    type: '创新创业类',
    credit: '1',
    score: '及格',
  },
  {
    grade: 0,
    time: '202001',
    name: '软件工程实践',
    type: '实践环节',
    credit: '1',
    score: '90',
  },
  {
    grade: 0,
    time: '202001',
    name: '数据库应用实践',
    type: '实践环节',
    credit: '1',
    score: '80',
  },
  {
    grade: 0,
    time: '202001',
    name: '计算机图形学综合实验',
    type: '实践选修',
    credit: '1.5',
    score: '81',
  },
  {
    grade: 0,
    time: '201902',
    name: '马克思主义基本原理',
    type: '公共必修',
    credit: '3',
    score: '80',
  },
  {
    grade: 0,
    time: '201902',
    name: '毛泽东思想和中国特色社会主义理论体系概论（下）',
    type: '公共必修',
    credit: '2',
    score: '83',
  },
  {
    grade: 0,
    time: '201902',
    name: '体育（四）',
    type: '公共必修',
    credit: '1',
    score: '91',
  },
  {
    grade: 0,
    time: '201902',
    name: '外教口语',
    type: '公共必修-英语拓展',
    credit: '2',
    score: '78',
  },
  {
    grade: 0,
    time: '201902',
    name: '形势与政策（四）',
    type: '公共必修',
    credit: '0',
    score: '80',
  },
  {
    grade: 0,
    time: '201902',
    name: '概率论与数理统计',
    type: '学科必修',
    credit: '3',
    score: '81',
  },
  {
    grade: 0,
    time: '201902',
    name: '计算机组成原理A',
    type: '学科必修',
    credit: '3.5',
    score: '81',
  },
  {
    grade: 0,
    time: '201902',
    name: '数据通信与计算机网络A',
    type: '学科必修',
    credit: '3.5',
    score: '75',
  },
  {
    grade: 0,
    time: '201902',
    name: '专家系列讲座',
    type: '专业必修（限选）',
    credit: '1',
    score: 60,
  },
  {
    grade: 0,
    time: '201902',
    name: '日常生活中的经济学',
    type: '人文社会科学类',
    credit: '2',
    score: 90,
  },
  {
    grade: 0,
    time: '201902',
    name: '投资理财入门与实战技巧',
    type: '人文社会科学类',
    credit: '2',
    score: '不及格',
  },
  {
    grade: 0,
    time: '201902',
    name: '超星尔雅：创业人生',
    type: '创新创业类',
    credit: '1',
    score: 80,
  },
  {
    grade: 0,
    time: '201902',
    name: '汇编语言程序设计',
    type: '实践环节',
    credit: '1.5',
    score: '72',
  },
  {
    grade: 0,
    time: '201902',
    name: '计算机组成原理实践',
    type: '实践环节',
    credit: '1',
    score: '83',
  },
  {
    grade: 0,
    time: '201902',
    name: '思想政治实践课',
    type: '实践环节',
    credit: '2',
    score: '82',
  },
  {
    grade: 0,
    time: '201902',
    name: '局域网技术实验',
    type: '实践选修',
    credit: '1',
    score: '80',
  },
  {
    grade: 0,
    time: '201901',
    name: '大学英语（四）',
    type: '公共必修',
    credit: '2',
    score: '75',
  },
  {
    grade: 0,
    time: '201901',
    name: '毛泽东思想和中国特色社会主义理论体系概论（上）',
    type: '公共必修',
    credit: '2',
    score: '74',
  },
  {
    grade: 0,
    time: '201901',
    name: '体育（三）',
    type: '公共必修',
    credit: '1',
    score: '72',
  },
  {
    grade: 0,
    time: '201901',
    name: '形势与政策（三）',
    type: '公共必修',
    credit: '0',
    score: '85',
  },
  {
    grade: 0,
    time: '201901',
    name: '大学物理A（下）',
    type: '学科必修',
    credit: '3.5',
    score: '67',
  },
  {
    grade: 0,
    time: '201901',
    name: '计算机学科导论',
    type: '学科必修',
    credit: '1.5',
    score: '76',
  },
  {
    grade: 0,
    time: '201901',
    name: '离散数学A',
    type: '学科必修',
    credit: '4',
    score: '82',
  },
  {
    grade: 0,
    time: '201901',
    name: '数字电路与逻辑设计',
    type: '学科必修',
    credit: '2.5',
    score: '71',
  },
  {
    grade: 0,
    time: '201901',
    name: '算法与数据结构',
    type: '学科必修',
    credit: '3.5',
    score: '80',
  },
  {
    grade: 0,
    time: '201901',
    name: '线性代数',
    type: '学科必修',
    credit: '2',
    score: '63',
  },
  {
    grade: 0,
    time: '201901',
    name: '羽毛球',
    type: '人文社会科学类',
    credit: '1',
    score: 80,
  },
  {
    grade: 0,
    time: '201901',
    name: '英语会话实践',
    type: '文学与艺术类',
    credit: '1.5',
    score: 90,
  },
  {
    grade: 0,
    time: '201901',
    name: '大学物理实验A（下）',
    type: '实践环节',
    credit: '1',
    score: '73',
  },
  {
    grade: 0,
    time: '201901',
    name: '认知实习',
    type: '实践环节',
    credit: '1',
    score: '78',
  },
  {
    grade: 0,
    time: '201901',
    name: '数字逻辑电路设计',
    type: '实践环节',
    credit: '1.5',
    score: '83',
  },
  {
    grade: 0,
    time: '201901',
    name: '算法与数据结构实践',
    type: '实践环节',
    credit: '1',
    score: '92',
  },
  {
    grade: 0,
    time: '201802',
    name: '大学英语（三）',
    type: '公共必修',
    credit: '2',
    score: '81',
  },
  {
    grade: 0,
    time: '201802',
    name: '思想道德修养与法律基础（下）',
    type: '公共必修',
    credit: '1',
    score: '75',
  },
  {
    grade: 0,
    time: '201802',
    name: '体育（二）',
    type: '公共必修',
    credit: '1',
    score: '73',
  },
  {
    grade: 0,
    time: '201802',
    name: '形势与政策（二）',
    type: '公共必修',
    credit: '0',
    score: '85',
  },
  {
    grade: 0,
    time: '201802',
    name: '大学物理A（上）',
    type: '学科必修',
    credit: '3',
    score: '60',
  },
  {
    grade: 0,
    time: '201802',
    name: '高等数学B（下）',
    type: '学科必修',
    credit: '5',
    score: '76',
  },
  {
    grade: 0,
    time: '201802',
    name: '高级语言程序设计',
    type: '学科必修',
    credit: '2.5',
    score: '87',
  },
  {
    grade: 0,
    time: '201802',
    name: '基础电路与电子学',
    type: '学科必修',
    credit: '4',
    score: '84',
  },
  {
    grade: 0,
    time: '201802',
    name: '面向对象程序设计',
    type: '学科必修',
    credit: '3',
    score: '72',
  },
  {
    grade: 0,
    time: '201802',
    name: 'Python程序设计',
    type: '专业选修',
    credit: '2',
    score: '78',
  },
  {
    grade: 0,
    time: '201802',
    name: '感悟趋势之美—未来经济大趋势分析',
    type: '人文社会科学类',
    credit: '2',
    score: 80,
  },
  {
    grade: 0,
    time: '201802',
    name: '学银在线：人文视野中的科学技术——自然辩证法',
    type: '人文社会科学类',
    credit: '2',
    score: 80,
  },
  {
    grade: 0,
    time: '201802',
    name: '证券投资理论与实务',
    type: '人文社会科学类',
    credit: '2',
    score: 80,
  },
  {
    grade: 0,
    time: '201802',
    name: '程序设计语言综合设计',
    type: '实践环节',
    credit: '1',
    score: '73',
  },
  {
    grade: 0,
    time: '201802',
    name: '大学物理实验A（上）',
    type: '实践环节',
    credit: '1.5',
    score: '76',
  },
  {
    grade: 0,
    time: '201802',
    name: '电子线路综合实验',
    type: '实践环节',
    credit: '1.5',
    score: 90,
  },
  {
    grade: 0,
    time: '201802',
    name: '高级语言程序设计实践',
    type: '实践环节',
    credit: '1',
    score: '78',
  },
  {
    grade: 0,
    time: '201801',
    name: '大学生心理健康教育',
    type: '公共必修',
    credit: '1',
    score: '75',
  },
  {
    grade: 0,
    time: '201801',
    name: '大学生职业生涯规划',
    type: '公共必修',
    credit: '0.5',
    score: '75',
  },
  {
    grade: 0,
    time: '201801',
    name: '大学英语（二）',
    type: '公共必修',
    credit: '2',
    score: '79',
  },
  {
    grade: 0,
    time: '201801',
    name: '军事理论',
    type: '公共必修',
    credit: '1',
    score: '89',
  },
  {
    grade: 0,
    time: '201801',
    name: '思想道德修养与法律基础（上）',
    type: '公共必修',
    credit: '1',
    score: '88',
  },
  {
    grade: 0,
    time: '201801',
    name: '体育（一）',
    type: '公共必修',
    credit: '1',
    score: '63',
  },
  {
    grade: 0,
    time: '201801',
    name: '形势与政策（一）',
    type: '公共必修',
    credit: '0',
    score: 80,
  },
  {
    grade: 0,
    time: '201801',
    name: '中国近现代史纲要',
    type: '公共必修',
    credit: '3',
    score: '65',
  },
  {
    grade: 0,
    time: '201801',
    name: '高等数学B（上）',
    type: '学科基础必修课',
    credit: '5',
    score: '83',
  },
  {
    grade: 0,
    time: '201801',
    name: '工程制图D',
    type: '任意选修课',
    credit: '3.5',
    score: '67',
  },
  {
    grade: 0,
    time: '201801',
    name: '无机化学B',
    type: '任意选修课',
    credit: '2',
    score: '78',
  },
  {
    grade: 0,
    time: '201801',
    name: '无机化学实验B',
    type: '任意选修课',
    credit: '1',
    score: '80',
  },
  {
    grade: 0,
    time: '201801',
    name: '军事训练',
    type: '实践环节',
    credit: '1',
    score: '82',
  },
];
